### ISSUE TITLE
Overwriting the global log function results in a exception.

### ISSUE THREAD

**Issue by Vayner** [zlovred/ZGroupChange#8]
Overwriting the global log function results in an exception in Factorio 0.14.12.

**Comment by ravenwing210** [comment]
It seems that the log function has been protected since approx. Factorio 0.14.8. Someone on the mods portal said they were able to fix the issue by "renaming the function" but I don't have to knowledge of Lua to do it properly for myself.

(This is an FYI and also hopefully a bump @ the devs because I would love to see this updated. The friggin crafting menu in vanilla is a disaster and only gets worse as you mod, this would be a godsend if it still worked.)

**Comment by Vayner** [comment]
It appears it was fixed in version 1.2.6.
